version: "3.9"
services:

  backup-15-2:
    build:
      context: .
      args:
        POSTGRES_VERSION: 15.2
    depends_on:
      - database-15-2
    environment:
      - POSTGRES_PASSWORD=SumPassw0rdHere
      - POSTGRES_DB=postgres
      - PGHOST=database-15-2 # The hostname of the PostgreSQL database to dump
      - CRON_SCHEDULE=*/5 * * * * # Every 5 minutes
      - RETAIN_COUNT=3 # Keep this number of backups
#      - S3_BUCKET_PATH=s3://${S3_BUCKET_NAME}/
#      - S3_SECRET_KEY=${S3_SECRET_KEY}
#      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
    volumes:
      - ./persistent/dump/15-2:/dump
    restart: unless-stopped

  backup-12-16:
    build:
      context: .
      args:
        POSTGRES_VERSION: 12.16
    depends_on:
      - database-12-16
    environment:
      - POSTGRES_PASSWORD=SumPassw0rdHere
      - POSTGRES_DB=postgres
      - PGHOST=database-12-16 # The hostname of the PostgreSQL database to dump
      - CRON_SCHEDULE=*/5 * * * * # Every 5 minutes
      - RETAIN_COUNT=3 # Keep this number of backups
#      - S3_BUCKET_PATH=s3://${S3_BUCKET_NAME}/
#      - S3_SECRET_KEY=${S3_SECRET_KEY}
#      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
    volumes:
      - ./persistent/dump/12-16:/dump
    restart: unless-stopped

  database-12-16:
    image: postgres:12.16
    environment:
      - POSTGRES_PASSWORD=SumPassw0rdHere
      - POSTGRES_DB=postgres
    volumes:
      - ./persistent/12-16:/var/lib/postgresql/data

  database-15-2:
    image: postgres:15.2
    environment:
      - POSTGRES_PASSWORD=SumPassw0rdHere
      - POSTGRES_DB=postgres
    volumes:
      - ./persistent/15-2:/var/lib/postgresql/data
