version: "3.9"
services:
  backup:
    build: .
    volumes:
      - ./persistent/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=SumPassw0rdHere
      - POSTGRES_DB=postgres
      - PGHOST=database # The hostname of the PostgreSQL database to dump
      - CRON_SCHEDULE=0 3 * * * # Every day at 3am
      - RETAIN_COUNT=1 # Keep this number of backups
    restart: unless-stopped

  database:
    image: postgres:12.14
    environment:
      - POSTGRES_PASSWORD=SumPassw0rdHere
      - POSTGRES_DB=postgres
    volumes:
      - ./persistent/data:/dump
