name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-all:
    strategy:
      matrix:
        version: [9.6, 10.17, 11.12, 12.1, 12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.10, 13.0, 13.1, 13.6, 14.2]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: bld-and-push@v1
      with:
        POSTGRES_VERSION: ${{ matrix.version }}

  build-latest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: bld-and-push@v1
      with:
        POSTGRES_VERSION: latest
