name: Docker Image CI

on:
  schedule:
    - cron: '0 5 * * *'
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  DOCKER_REG: brconn98

jobs:

  bld-and-push:
    strategy:
      matrix:
        version: [9.6, 11.12, 12.1, 12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.10, 13.0, 13.1, 13.6, 14.2, latest]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --build-arg POSTGRES_VERSION=${{ matrix.version }} -t ${{ env.DOCKER_REG }}/pg_dump:${{ matrix.version }} --file Dockerfile
    - name: Log into docker.io
      if: github.event_name != 'pull_request'
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
        registry: docker.io
        username: ${{ env.DOCKER_REG }}
        password: ${{ secrets.DOCKER_PAT }}
    - name: Push the Docker image
      run: docker push ${{ env.DOCKER_REG }}/pg_dump:${{ matrix.version }}
